from django.urls import path
from .views import *

urlpatterns = [
    path("", login_view, name="login"),
    path("hod/", hod_dashboard, name="hod"),
    path("add_student/", add_student, name="add_student"),
    path("add_staff/", add_staff, name="add_staff"),
    path("manage_student/", manage_student, name="manage_student"),
    path("manage_staff/", manage_staff, name="manage_staff"),
    path("add_course/", add_course, name="add_course"),
    path("add_subject/", add_subject, name="add_subject"),
    path("manage_course/", manage_course, name="manage_course"),
    path("edit_course/<str:pk>/", edit_course, name="edit_course"),
    path("manage_session/", manage_session, name="manage_session"),
    path("manage_subject/", manage_subject, name="manage_subject"),
    path("edit_session/<str:pk>/", edit_session, name="edit_session"),
    path("edit_subject/<str:pk>/", edit_subject, name="edit_subject"),
    path("edit_leave/<str:pk>/", edit_leave, name="edit_leave"),
    path("save_course/<str:pk>/", save_course, name="save_course"),
    path("save_leave/<str:pk>/", save_leave, name="save_leave"),
    path("save_session/<str:pk>/", save_session, name="save_session"),
    path("save_subject/<str:pk>/", save_subject, name="save_subject"),
    path("delete_course/<str:pk>/", delete_course, name="delete_course"),
    path("delete_session/<str:pk>/", delete_session, name="delete_session"),
    path("delete_subject/<str:pk>/", delete_subject, name="delete_subject"),
    path(
        "student_leave_accept/<str:pk>/",
        student_leave_accept,
        name="student_leave_accept",
    ),
    path("staff_leave/", staff_leave, name="staff_leave"),
    path(
        "student_leave_reject/<str:pk>/",
        student_leave_reject,
        name="student_leave_reject",
    ),
    path(
        "staff_leave_accept/<str:pk>/",
        staff_leave_accept,
        name="staff_leave_accept",
    ),
    path(
        "staff_leave_reject/<str:pk>/",
        staff_leave_reject,
        name="staff_leave_reject",
    ),
    path("add_session/", add_session, name="add_session"),
    path("manage_session/", manage_session, name="manage_session"),
    path("student_feedback/", student_feedback, name="student_feedback"),
    path("staff_feedback/", staff_feedback, name="staff_feedback"),
    path("student_leave/", student_leave, name="student_leave"),
    path("custom_logout/", custom_logout, name="custom_logout"),
    path("edit_feedback/<str:pk>/", edit_feedback, name="edit_feedback"),
    path("save_feedback/<str:pk>/", save_feedback, name="save_feedback"),
]
