# Generated by Django 4.2.7 on 2024-05-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionyearmodel',
            old_name='course_id',
            new_name='session_id',
        ),
    ]
