# Generated by Django 4.2.7 on 2024-05-25 19:48

import college_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0004_rename_course_id_sessionyearmodel_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=college_app.models.generate_image_path),
        ),
    ]
