# Generated by Django 4.2.7 on 2024-05-25 19:50

import college_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0005_staff_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=college_app.models.generate_staff_image_path),
        ),
    ]
