# Generated by Django 4.2.7 on 2024-05-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0007_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='suject_id',
            new_name='subject_id',
        ),
    ]
