# Generated by Django 4.2.7 on 2024-05-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0009_attendance_studentresult_leavereportstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.CharField(max_length=255),
        ),
    ]
