# Generated by Django 4.2.7 on 2024-05-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0011_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
